services:
  - type: web
    name: etf-dashboard
    env: python
    plan: free
    buildCommand: pip install -r render_minimal/requirements.txt
    startCommand: gunicorn render_minimal.wsgi:app
    envVars:
      - key: DB_PATH
        value: etf_history.db
